In [8]:
%pip install --upgrade ultralytics


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
%pip install -r requirements.txt
%pip install torch torchvision torchaudio
%pip install -U ultralytics 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


     ---------------------------------------- 0.0/41.8 kB ? eta -:--:--
     ---------------------------------------  41.0/41.8 kB 1.9 MB/s eta 0:00:01
     -------------------------------------- 41.8/41.8 kB 404.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/871.6 kB ? eta -:--:--
   --- ------------------------------------ 81.9/871.6 kB 1.5 MB/s eta 0:00:01
   ----- ---------------------------------- 112.6/871.6 kB 1.1 MB/s eta 0:00:01
   ------ --------------------------------- 143.4/871.6 kB 1.1 MB/s eta 0:00:01
   ------- ------------------------------ 174.1/871.6 kB 952.6 kB/s eta 0:00:01
   ----------- ---------------------------- 256.0/871.6 kB 1.1 MB/s eta 0:00:01
   --------------- ------------------------ 327.7/871.6 kB 1.1 MB/s eta 0:00:01
   ---------------- ----------------------- 368.6/871.6 kB 1.1 MB/s eta 0:00:01
   ----------------- ---------------------- 389.1/871.6 kB 1.1 MB/s eta 0:00:01
   ----------------------- ---------------- 501.8/871.6 kB


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!python detect.py --weights best.onnx --img 640 --conf 0.5 --source Data.jpeg --device cpu 

requirements: C:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\requirements.txt not found, check failed.
tensor([[1.17100e+03, 5.49000e+02, 1.22200e+03, 6.53000e+02, 9.36341e-01, 4.00000e+00],
        [9.61000e+02, 5.47000e+02, 1.03900e+03, 6.52000e+02, 9.34804e-01, 5.00000e+00],
        [9.62000e+02, 4.87000e+02, 1.04000e+03, 7.93000e+02, 9.24720e-01, 7.00000e+00],
        [1.10100e+03, 4.79000e+02, 1.14900e+03, 5.55000e+02, 9.18704e-01, 2.00000e+00],
        [1.17400e+03, 4.94000e+02, 1.22300e+03, 8.09000e+02, 9.17854e-01, 7.00000e+00],
        [1.08200e+03, 5.50000e+02, 1.16900e+03, 6.88000e+02, 8.88084e-01, 5.00000e+00],
        [1.07600e+03, 4.78000e+02, 1.16500e+03, 8.26000e+02, 8.50776e-01, 7.00000e+00]])
tensor([[9.62000e+02, 5.46000e+02, 1.04000e+03, 6.51000e+02, 9.42159e-01, 5.00000e+00],
        [9.61000e+02, 4.90000e+02, 1.03800e+03, 7.90000e+02, 9.28084e-01, 7.00000e+00],
        [1.10600e+03, 4.75000e+02, 1.15100e+03, 5.49000e+02, 9.11904e-01, 2.000

detect: weights=['best.onnx'], source=data.mp4, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  7287db0 Python-3.11.0 torch-2.1.0+cu118 CPU

Loading best.onnx for ONNX Runtime inference...
video 1/1 (1/131) C:\Jaket-Kumbang\yolov5\data.mp4: 640x640 1 devina, 1 jaket kumbang, 2 jaket lains, 3 manusias, 149.6ms
video 1/1 (2/131) C:\Jaket-Kumbang\yolov5\data.mp4: 640x640 1 devina, 1 jaket kumbang, 2 jaket lains, 3 manusias, 129.8ms
video 1/1 (3/131) C:\Jaket-Kumbang\yolov5\data.mp4: 640x640 1 devina, 1 jaket kumbang, 2 jaket lains, 4 manusias, 116.7ms
video 1/1 (4/131) C:\Jaket-Kumbang\yolov5\data.mp4: 640x640 1 devina, 2 jaket lains, 3 m

In [6]:
!python detect.py --weights jaket.onnx --img 640 --conf 0.25 --source jaket.jpeg --device cpu 

detect: weights=['jaket.onnx'], source=0, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  v7.0-347-gd6112173 Python-3.11.0 torch-2.1.0+cu118 CPU

Loading jaket.onnx for ONNX Runtime inference...
WARNING  Environment does not support cv2.imshow() or PIL Image.show()
OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1272: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

1/1: 0... 

In [10]:
import cv2
import numpy as np

# Load your ONNX model
model_path = 'jaket.onnx'
net = cv2.dnn.readNet(model_path)

# Set up webcam
cap = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    if not ret:
        break

    # Prepare the frame for detection
    blob = cv2.dnn.blobFromImage(frame, scalefactor=1/255.0, size=(640, 640), swapRB=True, crop=False)
    net.setInput(blob)
    
    # Perform detection
    detections = net.forward()
    
    # Process detections
    for detection in detections[0, 0]:
        confidence = detection[2]
        if confidence > 0.25:  # Confidence threshold
            box = detection[3:7] * np.array([frame.shape[1], frame.shape[0], frame.shape[1], frame.shape[0]])
            (x, y, x_max, y_max) = box.astype("int")
            
            # Draw the bounding box and label on the frame
            cv2.rectangle(frame, (x, y), (x_max, y_max), (0, 255, 0), 2)
            label = f"Confidence: {confidence:.2f}"
            cv2.putText(frame, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
    
    # Display the resulting frame
    cv2.imshow('Webcam Frame', frame)
    
    # Break the loop on 'q' key press
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the capture and close windows
cap.release()
cv2.destroyAllWindows()


error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'


kemeja 1
jaket 0

In [13]:
!python detect.py --weights kumbang.onnx --img 640 --conf 0.25 --source kemeja.jpeg --device cpu 

tensor([[ 45.00000,  26.00000, 632.00000, 530.00000,   0.75849,   0.00000]])


detect: weights=['kumbang.onnx'], source=kemeja.jpeg, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  v7.0-347-gd6112173 Python-3.11.0 torch-2.1.0+cu118 CPU

Loading kumbang.onnx for ONNX Runtime inference...
image 1/1 C:\Jaket-Kumbang\yolov5\kemeja.jpeg: 640x640 1 jaket lain, 106.7ms
Speed: 4.0ms pre-process, 106.7ms inference, 3.0ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs\detect\exp10


In [14]:
!python detect.py --weights kumbang.onnx --img 640 --conf 0.25 --source kumbang.jpeg --device cpu 

tensor([[9.70000e+01, 8.30000e+01, 7.11000e+02, 8.53000e+02, 8.45072e-01, 1.00000e+00]])


detect: weights=['kumbang.onnx'], source=kumbang.jpeg, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  v7.0-347-gd6112173 Python-3.11.0 torch-2.1.0+cu118 CPU

Loading kumbang.onnx for ONNX Runtime inference...
image 1/1 C:\Jaket-Kumbang\yolov5\kumbang.jpeg: 640x640 1 jaket-kumbang, 108.3ms
Speed: 4.0ms pre-process, 108.3ms inference, 3.0ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs\detect\exp11


jaket lain 0
jaket kumbang 1

if ke-1 Membedakan Best.pt jaket/kumbang
jaket:  if 0:run Best.pt kumbang
        if 1:Break
kumbang:if 0:run Klasifikasi wajah
        if 1:break

In [6]:
pip install onnx onnxruntime


   ---------------------------------------- 0.0/5.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.6 MB 1.4 MB/s eta 0:00:05
   ---------------------------------------- 0.0/5.6 MB 1.4 MB/s eta 0:00:05
    --------------------------------------- 0.1/5.6 MB 563.7 kB/s eta 0:00:10
    --------------------------------------- 0.1/5.6 MB 563.7 kB/s eta 0:00:10
    --------------------------------------- 0.1/5.6 MB 563.7 kB/s eta 0:00:10
    --------------------------------------- 0.1/5.6 MB 386.4 kB/s eta 0:00:15
    --------------------------------------- 0.1/5.6 MB 415.1 kB/s eta 0:00:14
   - -------------------------------------- 0.2/5.6 MB 418.0 kB/s eta 0:00:13
   - -------------------------------------- 0.2/5.6 MB 418.0 kB/s eta 0:00:13
   - -------------------------------------- 0.2/5.6 MB 384.3 kB/s eta 0:00:15
   - -------------------------------------- 0.2/5.6 MB 384.3 kB/s eta 0:00:15
   - -------------------------------------- 0.2/5.6 MB 409.6 kB/s eta 0:00:14


[notice] A new release of pip is available: 23.3.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
